CREATE TABLE DEPARTMENT_STORE(
DEP_STORE_ID INT PRIMARY KEY,
NAME_DEP_STORE VARCHAR(50));

CREATE TABLE CITY(
CITY_ID INT,
DEP_STORE_ID INT,
NAME_CITY VARCHAR(50),
PRIMARY KEY(CITY_ID),
CONSTRAINT DEP_STORE_ID FOREIGN KEY (DEP_STORE_ID)
REFERENCES DEPARTMENT_STORE (DEP_STORE_ID));

CREATE TABLE STORE(
STORE_ID INT PRIMARY KEY,
STORE_NAME VARCHAR(50),
ADRESS VARCHAR(50),
CITY INT FOREIGN KEY REFERENCES CITY(CITY_ID)
);

CREATE TABLE ITEM(
ITEM_ID INT PRIMARY KEY,
ITEM_NAME VARCHAR(50),
CLASS VARCHAR(50),
STORE INT FOREIGN KEY REFERENCES STORE(STORE_ID));

CREATE TABLE CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50),
CUSTOMER_ORDER INT FOREIGN KEY REFERENCES ITEM(ITEM_ID));

CREATE TABLE HEADQUARTER(
HEADQUARTER_ID INT PRIMARY KEY,
HEADQUARTER_NAME VARCHAR(50),
ADRESS VARCHAR(50));

ALTER TABLE CITY
	ADD HEADQUAR_ID INT UNIQUE
	CONSTRAINT FK_HEADQUARTER_ID
		FOREIGN KEY (HEADQUAR_ID) 
		REFERENCES HEADQUARTER(HEADQUARTER_ID);

/*
ALTER TABLE CITY
DROP CONSTRAINT FK_HEADQUARTER_ID;

ALTER TABLE CITY
DROP COLUMN HEADQUAR_ID;

ALTER TABLE CITY
DROP CONSTRAINT UC_HEADQUARTER_ID;
*/